import os
from datetime import datetime

class ReportManager:
    def __init__(self, output_dir="reports"):
        # Create a reports directory if it doesn't exist
        self.output_dir = output_dir
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)
        
        # Initialize an empty report for the current session
        self.current_report = ""

    def start_new_report(self, target):
        """
        Starts a new report file for a specific target.
        """
        timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        self.filename = f"{self.output_dir}/report_{target}_{timestamp}.txt"
        
        header = f"""
================================================================================
AR-GHOSTNET SYSTEM REPORT
Target: {target}
Date: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Status: INITIALIZING SCAN
================================================================================
"""
        self.current_report = header
        self.save_report()
        return f"Report initialized: {self.filename}"

    def add_finding(self, category, data):
        """
        Adds a specific finding to the report.
        Example category: 'OPEN PORTS', 'SENSITIVE FILES', 'SQLi'
        """
        entry = f"\n[+] CATEGORY: {category}\n{'-' * 30}\n{data}\n"
        self.current_report += entry
        self.save_report()

    def save_report(self):
        """
        Writes the current report state to the physical file.
        """
        try:
            with open(self.filename, "w", encoding="utf-8") as f:
                f.write(self.current_report)
        except Exception as e:
            print(f"[-] Error saving report: {e}")

    def finalize_report(self):
        """
        Adds a closing footer to the report.
        """
        footer = f"\n\n================================================================================\n"
        footer += f"SCAN COMPLETED AT: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        footer += "Generated by AR-GhostNet Framework\n"
        footer += "================================================================================\n"
        self.current_report += footer
        self.save_report()
        return f"Report finalized and saved to: {self.filename}"

# Example Usage:
# rm = ReportManager()
# rm.start_new_report("google.com")
# rm.add_finding("PORT SCAN", "Port 80: Open, Port 443: Open")
# rm.finalize_report()